### PR TITLE
proguard rules in demo project

### PR DESCRIPTION
**Pull request by talklittle**

### CODE REVIEW

**Comment by EricKuck** [comment]
I don't think this proguard config is going to cover quite everything. For instance, generated classes for abstract classes do not extend `JsonObjectMapper`, so they could get removed. I believe this would cover everything (although I haven't tested it too much):

```
-keep class com.bluelinelabs.logansquare.** { *; }
-keep class **$$JsonObjectMapper { *; }
```

**Comment by talklittle** [comment]
@EricKuck Thank you for the feedback. I've updated the PR with your broader rules. Good to know about how abstract classes are handled.

**Comment by EricKuck** [comment]
I'm not the best with proguard configs, so excuse my ignorant question, but what does 

`-keep @com.bluelinelabs.logansquare.annotation.JsonObject class *`

do? Does it keep the annotations around at runtime?

**Comment by talklittle** [comment]
It keeps the class names of classes annotated with `@JsonObject`. So that they can be associated with their corresponding `$$JsonObjectMapper` class.

Otherwise e.g. `com.example.MyModel` becomes `com.example.a` and then `Class.forName(com.example.a$$JsonObjectMapper)` will break.

**Comment by EricKuck** [comment]
Ah, genius. The `@JsonObject` annotation is only around for compile time though, so I would think that it wouldn't even be there by the time Proguard processes it. Have you tested it out? Not doubting you, just surprised that would work.

**Comment by talklittle** [comment]
Yes, the purpose of the original line

    -keep class com.bluelinelabs.logansquare.annotation.**

Was to keep the `@JsonObject` annotation around so that I could use it in conjunction with the

    -keep @com.bluelinelabs.logansquare.annotation.JsonObject class *

Somehow it works, which surprised me too. It did take some trial and error to find the correct combination of rules.

**Comment by talklittle** [comment]
I've added commits and tested using

    ./gradlew assembleRelease

and then looking at `BenchmarkDemo/app/build/outputs/mapping/release/mapping.txt` to see that the `JsonObject` annotation, `Response` and `Response$$JsonObjectMapper` are all kept and not renamed.

**Comment by EricKuck** [comment]
Wow, awesome work! I'll update the README.md file with your findings.

**Comment by EricKuck** [comment]
Oh, last question - what's `-dontwarn org.w3c.dom.bootstrap.DOMImplementationRegistry` for? I don't usually see any issues with Jackson. From what I can tell from a quick Google search, it appears to be for Jackson Databind, which this library doesn't use.

**Comment by EricKuck** [comment]
Nevermind, the benchmark app obviously does use Databind for comparison. Got it!

**Comment by talklittle** [comment]
@EricKuck Thank you!

**Pull request merged**
