### PR TITLE
Add cached Gson and Jackson parsers to benchmark demo

### PR DESCRIPTION
**Pull request by ronocod**
This addresses the issue I raised in issue https://github.com/bluelinelabs/LoganSquare/issues/33 and shows the results for cached Gson and Jackson parsers in the benchmark demo

### CODE REVIEW

**Comment by EricKuck** [comment]
Thanks for submitting! I'll be away from a computer until Monday, but I'll take a quick look through and merge it in then.

**Comment by EricKuck** [comment]
Hey sorry about the wait. Your changes look great. After I thought about it some more, the current benchmarks (the ones I wrote) are kind of disingenuous. This wasn't at all intentional, I just wrote them as an afterthought. In real-world apps, no one is going to not cache their Gson or ObjectMapper instances, so yours are much more realistic.

I want you to get the credit for fixing the benchmarks by accepting your pull request, but I'd like to just replace the benchmarks I wrote with the ones you wrote. Do you mind making that change quickly?

**Comment by ronocod** [comment]
No problem, I'll make the change now.

**Comment by ronocod** [comment]
Everything should be good to go now!

Yeah the instance caching is a super easy thing to overlook I think, it was a few days after I first looked through the benchmark code until I even considered it. 

Good to see that LoganSquare is still the fastest even in the new benchmarks :smile:

**Comment by EricKuck** [comment]
Awesome, thanks! Guess I gotta update the readme now so I don't look like I'm just pulling number out of thin air :)

**Pull request merged**
